name: Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  push-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Push Docker Image
        run: |
          ./gradlew jib \
          -Djib.to.auth.username=${{secrets.DOCKERHUB_USER_NAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_HUB_PASSWORD}}