spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/ses_mock
    username: docker
    password: docker
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql