spring:
  datasource:
    url: jdbc:h2:mem:ses_mock
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      schema-locations: classpath:sql/h2/schema.sql
